<a href="https://colab.research.google.com/github/veequal/data-science-week1/blob/main/python2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Create a 2x2 array
array_2x2 = np.array([[1, 2], [3, 4]])

print(array_2x2)

[[1 2]
 [3 4]]


In [13]:
import numpy as np
# Create a 3x4 array with random values between 0 and 1
random_array = np.random.rand(3, 4)
print(random_array)


[[0.79189746 0.49292025 0.98855229 0.81107424]
 [0.96810239 0.23202821 0.52041599 0.32882529]
 [0.7087334  0.90065995 0.69473567 0.58273745]]


In [17]:
import numpy as np
# array of ones (3x3)
ones_array = np.ones((3, 3))
print(ones_array)
# array of zeros (2x2)
zeros_array = np.zeros((2, 2))
print(zeros_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [32]:
import numpy as np

# Create a 6x3 array with random values
random_array = np.random.rand(6, 3)

# Transpose the array
transposed_array = random_array.T

print(r"Original 6x3 array:\n", random_array)
print(r"\nTransposed 3x6 array:\n", transposed_array)


Original 6x3 array:\n [[0.85189256 0.6675453  0.01439091]
 [0.30328198 0.36001716 0.97509058]
 [0.42989081 0.63478677 0.80268876]
 [0.69292453 0.07315401 0.64332972]
 [0.03606967 0.76845638 0.5252644 ]
 [0.89495276 0.58261476 0.70874688]]
\nTransposed 3x6 array:\n [[0.85189256 0.30328198 0.42989081 0.69292453 0.03606967 0.89495276]
 [0.6675453  0.36001716 0.63478677 0.07315401 0.76845638 0.58261476]
 [0.01439091 0.97509058 0.80268876 0.64332972 0.5252644  0.70874688]]


In [31]:
import numpy as np
# set dimenisions
n, p, m = 6, 5, 9
# creat random array
A = np.random.rand(n, p) # shape (n, p)
B = np.random.rand(p, m) # shape (p, m)
# compute dot products
result = np.dot(A, B) # shape (n, m)
print(r"Array A (n, p):\n" , A)
print(r"\Array B (p, m):\n " , B)
print(r"\nDot Product (n, m):\n" , result)

Array A (n, p):\n [[0.02163977 0.92372368 0.76302109 0.66716031 0.08233729]
 [0.86840831 0.2018237  0.76315217 0.63808293 0.10151326]
 [0.37552086 0.18326057 0.82213915 0.72412485 0.84075893]
 [0.55824967 0.74937957 0.72371585 0.80865499 0.62108307]
 [0.97442338 0.74922667 0.44785396 0.35148342 0.17015659]
 [0.13294939 0.05651403 0.04077715 0.09160735 0.68568712]]
\Array B (p, m):\n  [[0.84867798 0.79158008 0.26867329 0.44368229 0.32784878 0.74464188
  0.79999668 0.13793396 0.99616237]
 [0.8369638  0.00350934 0.88034459 0.89168584 0.29069736 0.95990343
  0.11856033 0.68866015 0.33698768]
 [0.08241789 0.36850837 0.30403327 0.3567139  0.21741467 0.95606861
  0.88732998 0.00225964 0.95206823]
 [0.27074166 0.64883245 0.74766368 0.13500081 0.93422399 0.22982369
  0.77878171 0.76319206 0.6977895 ]
 [0.77241982 0.90743116 0.54992927 0.29328153 0.54728773 0.68110836
  0.08407387 0.37044179 0.12557978]]
\nDot Product (n, m):\n [[1.09860211 0.80914161 1.59508419 1.21966793 1.10984994 1.84170978


In [30]:
# Step 1: Set up Git config
!git config --global user.email "lordaynon88@gmail.com"
!git config --global user.name "veequal"

# Step 2: Clone your GitHub repo
!git clone https://github.com/veequal/data-science-week1.git

# Step 3: Copy the notebook into the repo folder
!cp python2.ipynb data-science-week1/

# Step 4: Commit and push the notebook
%cd data-science-week1
!git add python2.ipynb
!git commit -m "Add python2.ipynb from Colab"
!git push origin main

Cloning into 'data-science-week1'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 2 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 4.25 KiB | 2.12 MiB/s, done.
Resolving deltas: 100% (1/1), done.
cp: cannot stat 'python2.ipynb': No such file or directory
/content/data-science-week1
fatal: pathspec 'python2.ipynb' did not match any files
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
