<a href="https://colab.research.google.com/github/veequal/data-science-week1/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Create a 2x2 array
array_2x2 = np.array([[1, 2], [3, 4]])

print(array_2x2)

[[1 2]
 [3 4]]


In [13]:
import numpy as np
# Create a 3x4 array with random values between 0 and 1
random_array = np.random.rand(3, 4)
print(random_array)


[[0.79189746 0.49292025 0.98855229 0.81107424]
 [0.96810239 0.23202821 0.52041599 0.32882529]
 [0.7087334  0.90065995 0.69473567 0.58273745]]


In [17]:
import numpy as np
# array of ones (3x3)
ones_array = np.ones((3, 3))
print(ones_array)
# array of zeros (2x2)
zeros_array = np.zeros((2, 2))
print(zeros_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [25]:
import numpy as np

# Create a 6x3 array with random values
random_array = np.random.rand(6, 3)

# Transpose the array
transposed_array = random_array.T

print("Original 6x3 array:\n", random_array)
print("\nTransposed 3x6 array:\n", transposed_array)


Original 6x3 array:
 [[0.37608182 0.59400119 0.80465168]
 [0.70442135 0.04587498 0.92478049]
 [0.78532955 0.80248473 0.68872267]
 [0.02373933 0.49255594 0.59446274]
 [0.62463487 0.4285132  0.27022691]
 [0.16183267 0.80785243 0.06875517]]

Transposed 3x6 array:
 [[0.37608182 0.70442135 0.78532955 0.02373933 0.62463487 0.16183267]
 [0.59400119 0.04587498 0.80248473 0.49255594 0.4285132  0.80785243]
 [0.80465168 0.92478049 0.68872267 0.59446274 0.27022691 0.06875517]]


In [28]:
import numpy as np
# set dimenisions
n, p, m = 6, 5, 9
# creat random array
A = np.random.rand(n, p) # shape (n, p)
B = np.random.rand(p, m) # shape (p, m)
# compute dot products
result = np.dot(A, B) # shape (n, m)
print("Array A (n, p):\n" , A)
print("\Array B (p, m):\n " , B)
print("\nDot Product (n, m):\n" , result)

Array A (n, p):
 [[0.19949207 0.80272809 0.87576307 0.42578812 0.60891247]
 [0.08381179 0.1547163  0.5306187  0.84521979 0.27057438]
 [0.0142361  0.6577953  0.16595875 0.87835957 0.42455969]
 [0.0726889  0.21819868 0.22710018 0.50023936 0.44301635]
 [0.47779981 0.76498769 0.49821407 0.28978132 0.66069981]
 [0.44903475 0.77846541 0.60859906 0.18132174 0.73742388]]
\Array B (p, m):
  [[0.73071505 0.49345766 0.6883697  0.26146294 0.48235072 0.58507192
  0.03188655 0.93023929 0.44390123]
 [0.07200125 0.41936259 0.04335829 0.17502383 0.58778443 0.10722667
  0.08560993 0.5061683  0.33326204]
 [0.22105627 0.32579636 0.23534746 0.40973779 0.46229288 0.35838664
  0.02831483 0.53945191 0.67583018]
 [0.96504674 0.25568462 0.84115187 0.79785223 0.8513047  0.85268916
  0.46851024 0.56638457 0.83312664]
 [0.50119007 0.1714765  0.44735108 0.59096614 0.88989591 0.47595379
  0.96285732 0.08214515 0.19388743]]

Dot Product (n, m):
 [[1.11324852 0.9336771  1.00878795 1.25105221 1.8772594  1.16953197
  0.

<>:10: SyntaxWarning: invalid escape sequence '\A'
<>:10: SyntaxWarning: invalid escape sequence '\A'
/tmp/ipython-input-1411355846.py:10: SyntaxWarning: invalid escape sequence '\A'
  print("\Array B (p, m):\n " , B)
